spring.application.name: spring-boot-config
server.port: 8585
my:
   greeting: hello
   list:
     values: One,Two,Three
db:
   values: default-value-test
   host: 127.0.0.1
   port: 1200
management.endpoints.web.exposure.include: "*"

app:
   name: My app
   description: Welcome to${app.name}

spring.profiles.active: test